services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/home/foresys/app

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./app/setting:/home/setting
  #   restart: always
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost"]
  #     interval: 1m30s
  #     timeout: 20s
  #     retries: 3
  #     start_period: 20s
  #   depends_on:
  #     - app
  #   logging:
  #     driver: "none"